custom_js:
  - //cdn.jsdelivr.net/gh/wallleap/cdn/js/love.js
  - //cdn.jsdelivr.net/gh/wallleap/cdn@latest/js/sakura.js

footer:
  statistics:
    enable: true
    source: "busuanzi"  # 可选 leancloud | busuanzi  根据自己需求选择
    pv_format: "总访问量 {} 次"  # 显示的文本，{}是数字的占位符（必须包含)，下同
    uv_format: "总访客数 {} 人"